wandb_version: 1

train_args:
  desc: null
  value:
    learning_rate: 0.0001
    anneal_lr: 1
    batch_size: 128
    grad_clip: 1.0
    ema_decay: 0.999
    use_amp: 0
    stage1_steps: 100000
    stage2_steps: 50000
    stage3_steps: 50000
    weight_rec: 1.0
    weight_kl: 1.0e-06
    weight_smpl_joints_rec: 10.0
    weight_joints_consistency: 10.0
    weight_transl_delta: 100.0
    weight_orient_delta: 100.0
    weight_joints_delta: 100.0
    weight_latent_rec: 1.0
    weight_feature_rec: 0.0
    resume_checkpoint: null
    log_interval: 1000
    val_interval: 10000
    save_interval: 50000
    use_predicted_joints: 0
model_args:
  desc: null
  value:
    arch: all_encoder
    ff_size: 1024
    num_layers: 7
    num_heads: 4
    dropout: 0.1
    normalize_before: false
    activation: gelu
    position_embedding: learned
    latent_dim:
    - 1
    - 256
    h_dim: 256
    nfeats: 276
data_args:
  desc: null
  value:
    cfg_path: ./config_files/config_hydra/motion_primitive/mp_h2_f8_r8.yaml
    data_dir: ./data/seq_data_zero_male
    dataset: mp_seq_v2
    prob_static: 0.0
    enforce_gender: male
    enforce_zero_beta: 1
    weight_scheme: text_samp:0.
    text_tolerance: 0.0
    history_length: 2
    future_length: 8
    num_primitive: 8
    feature_dim: 276
    body_type: smplx
exp_name:
  desc: null
  value: mvae_babel_smplx
seed:
  desc: null
  value: 0
torch_deterministic:
  desc: null
  value: true
device:
  desc: null
  value: cuda
save_dir:
  desc: null
  value: mvae/mvae_babel_smplx
track:
  desc: null
  value: 1
wandb_project_name:
  desc: null
  value: mld_vae
wandb_entity:
  desc: null
  value: MangoBox
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1762780103.0
    t:
      1:
      - 1
      - 33
      - 41
      - 55
      2:
      - 1
      - 33
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.18
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
